### ISSUE TITLE
Memory access fault when using hipMemcpyAsync

### ISSUE THREAD

**Issue by holyprince** [ROCm/HIP#1189]
When I running a ported program from cuda. I meet the problem.

```
Memory access fault by GPU node-4 (Agent handle: 0x14193b0) on address 0x2b43aa1be000. Reason: Page not present or supervisor privilege.
[e09r2n10:110000] *** Process received signal ***
[e09r2n10:110000] Signal: Aborted (6)
[e09r2n10:110000] Signal code:  (-6)
[e09r2n10:110000] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2ac05a3155e0]
[e09r2n10:110000] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x2ac05f5e31f7]
[e09r2n10:110000] [ 2] /lib64/libc.so.6(abort+0x148)[0x2ac05f5e48e8]
[e09r2n10:110000] [ 3] /opt/rocm/hsa/lib/libhsa-runtime64.so.1(+0x4857d)[0x2ac05b33357d]
[e09r2n10:110000] [ 4] /opt/rocm/hsa/lib/libhsa-runtime64.so.1(+0x48d7b)[0x2ac05b333d7b]
[e09r2n10:110000] [ 5] /opt/rocm/hsa/lib/libhsa-runtime64.so.1(+0x12f77)[0x2ac05b2fdf77]
[e09r2n10:110000] [ 6] /lib64/libpthread.so.0(+0x7e25)[0x2ac05a30de25]
[e09r2n10:110000] [ 7] /lib64/libc.so.6(clone+0x6d)[0x2ac05f6a634d]
[e09r2n10:110000] *** End of error message ***

```

And using gdb to debug have this following info :
```
(gdb) bt
#0  0x00002aaab0874107 in ioctl () from /lib64/libc.so.6
#1  0x00002aaab0b53ad8 in ?? () from /opt/rocm/lib64/libhsakmt.so.1
#2  0x00002aaab0b4ca3e in hsaKmtWaitOnMultipleEvents () from /opt/rocm/lib64/libhsakmt.so.1
#3  0x00002aaab0b4d059 in hsaKmtWaitOnEvent () from /opt/rocm/lib64/libhsakmt.so.1
#4  0x00002aaaac5005b2 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#5  0x00002aaaac50040a in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#6  0x00002aaaac4f2ad9 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#7  0x00002aaab2c9b2b4 in waitComplete () at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:4884
#8  0x00002aaab2ca139d in operator() () at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:5015
#9  __invoke_impl<void, (lambda at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:5014:77)> ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/invoke.h:60
#10 __invoke<(lambda at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:5014:77)> ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/invoke.h:95
#11 _M_invoke<0> () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/thread:234
#12 operator() () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/thread:243
#13 operator() () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:1362
#14 0x00002aaab2ca1332 in _M_invoke ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/std_function.h:301
#15 0x00002aaab2c92607 in operator() ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/std_function.h:706
#16 _M_do_set () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:561
#17 0x00002aaaab4e9e20 in pthread_once () from /lib64/libpthread.so.0
#18 0x00002aaab2ca1763 in __gthread_once ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/x86_64-redhat-linux/bits/gthr-default.h:699
#19 call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()> *, bool *), std::__future_base::_State_baseV2 *, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()> *, bool *> ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/mutex:684
#20 _M_set_result () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:401
#21 _M_complete_async () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:1615
#22 0x00002aaab2c6ef74 in wait ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:334
#23 wait () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:692
#24 wait () at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:1617
#25 0x00002aaab2c707e5 in copy_ext () at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:4131
#26 0x00002aaaabbdedeb in ihipStream_t::locked_copyAsync(void*, void const*, unsigned long, unsigned int) ()
   from /opt/rocm/hip/lib/libhip_hcc.so
#27 0x00002aaaabc9b566 in hipMemcpyAsync () from /opt/rocm/hip/lib/libhip_hcc.so
#28 0x000000000055d167 in void hipCpyDeviceToHost<hipFloatComplex>(hipFloatComplex*, hipFloatComplex*, unsigned long, ihipStream_t*&) ()
#29 0x000000000055cf64 in AccPtr<hipFloatComplex>::cpToHost() ()
#30 0x0000000000544be9 in void AccUtilities::normalizeAndTransformImage<MlOptimiserHip>(AccPtr<float>&, MultidimArray<tComplex<double> >&, MlOptimiserHip*, unsigned long, unsigned long, unsigned long, int) ()
---Type <return> to continue, or q <return> to quit---
#31 0x0000000000526eab in void getFourierTransformsAndCtfs<MlOptimiserHip>(long, OptimisationParamters&, SamplingParameters&, MlOptimiser*, MlOptimiserHip*, AccPtrFactory, int) ()
#32 0x00000000004ef0dc in void accDoExpectationOneParticle<MlOptimiserHip>(MlOptimiserHip*, unsigned long, int, AccPtrFactory) ()
#33 0x00000000004eeb70 in MlOptimiserHip::doThreadExpectationSomeParticles(int) ()
#34 0x00000000008cf483 in globalThreadExpectationSomeParticles(ThreadArgument&) ()
#35 0x00000000009e3a68 in _threadMain(void*) ()
#36 0x00002aaaab4e4e25 in start_thread () from /lib64/libpthread.so.0
#37 0x00002aaab087d34d in clone () from /lib64/libc.so.6

```

Does this information show that the hipMemcpyAsync copies hipFloatComplex has some error?
But if I just write a simple demo to test the function, it is right. So I want to ask how can I location the real error from the information?
Thank you very much!

**Comment by ppanchad-amd** [comment]
@holyprince Apologies for the lack of response.  Do you still require assistance with this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@holyprince Closing issue. Please re-open if you still require assistance. Thanks!
