### ISSUE TITLE
HIP hang when running NWChem with more than 8 process

### ISSUE THREAD

**Issue by yuq** [ROCm/HIP#777]
Similar to https://github.com/ROCm-Developer-Tools/HIP/issues/704

GPU: Vega10/Vega20
OS: Ubuntu 16.04
ROCM: 1.9.2 release

NWChem is an HPC application, we are porting it to HIP here:
https://github.com/hpc-app/nwchem

Install and run:
https://github.com/hpc-app/nwchem/wiki

Now it can build and run on ROCM stack with <= 4 process (mpirun -np 4). But when `mpirun -np 8`, it will hang in either `hipMemcpy` or `hipDeviceSynchronize` after a `hipLaunchKernelGGL`, the hang place is random.

When np>1, only process 0 will use GPU, and other processes will use CPU to compute, so seems there should be no affect on the GPU process, but it still hang.

Tried setting `HIP_LAUNCH_BLOCKING=1 HIP_API_BLOCKING=1`, same result.

Attach the backtrace when hang:
```
#0  0x00007f18e7fffe21 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#1  0x00007f18e7fffbea in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#2  0x00007f18e7ff2639 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#3  0x00007f18de1d7c21 in CopyHostToDeviceStaging () at /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.9/external/hcc-tot/lib/hsa/unpinned_copy_engine.cpp:318
#4  0x00007f18de189f58 in syncCopyExt () at /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.9/external/hcc-tot/lib/hsa/mcwamp_hsa.cpp:5367
#5  0x00007f18de188d98 in copy_ext () at /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.9/external/hcc-tot/lib/hsa/mcwamp_hsa.cpp:4055
#6  0x00007f18e82d53a6 in ihipStream_t::locked_copySync(void*, void const*, unsigned long, unsigned int, bool) () from /opt/rocm/lib/libhip_hcc.so
#7  0x00007f18e836abc6 in hipMemcpy () from /opt/rocm/lib/libhip_hcc.so
#8  0x0000000000453830 in sd_t_d2_4_cuda ()
#9  0x0000000000453eb9 in sd_t_d2_4_cuda_ ()
#10 0x0000000001cc8913 in ccsd_t_doubles_gpu_2_ ()
#11 0x0000000001ccb05a in ccsd_t_doubles_gpu_ ()
#12 0x0000000001ce2a9d in ccsd_t_gpu_ ()
#13 0x0000000002e8d715 in tce_energy (rtdb=0, excitedfragment=.TRUE.) at tce_energy.F:2781
#14 0x0000000002e7ef42 in tce_energy_fragment (rtdb=0) at tce_energy_fragment.F:88
#15 0x00000000004a6c95 in task_energy_doit (rtdb=0, theory=<error reading variable: Cannot access memory at address 0x7ffff3f2a000>, energy=6.0134700169990685e-154, _theory=_theory@entry=32)
    at task_energy.F:299
#16 0x00000000004a82df in task_energy (rtdb=0) at task_energy.F:122
#17 0x000000000049b571 in task (rtdb=0) at task.F:371
#18 0x0000000000493dcf in nwchem () at nwchem.F:318
#19 0x00000000004942cc in main (argc=argc@entry=2, argv=0x7ffff3f28dd5) at nwchem.F:402
#20 0x00007f18df643830 in __libc_start_main (main=0x4942af <main>, argc=2, argv=0x7ffff3f28448, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffff3f28438)
    at ../csu/libc-start.c:291
#21 0x000000000048fc99 in _start ()
```

```
#0  0x00007f18d5412f47 in ioctl () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f18d50fe518 in ?? () from /opt/rocm/lib/libhsakmt.so.1
#2  0x00007f18d50f85af in hsaKmtWaitOnMultipleEvents () from /opt/rocm/lib/libhsakmt.so.1
#3  0x00007f18d50f8b09 in hsaKmtWaitOnEvent () from /opt/rocm/lib/libhsakmt.so.1
#4  0x00007f18ddcf2dea in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#5  0x00007f18ddcf2bea in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#6  0x00007f18ddce5639 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#7  0x00007f18d3e9f28a in waitComplete () at /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.9/external/hcc-tot/lib/hsa/mcwamp_hsa.cpp:4762
#8  0x00007f18d3ea4a1d in operator() () at /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.9/external/hcc-tot/lib/hsa/mcwamp_hsa.cpp:4886
#9  _M_invoke<> () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:1530
#10 operator() () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:1520
#11 operator() () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/future:1342
#12 0x00007f18d3ea49b2 in _M_invoke () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:1856
#13 0x00007f18d3e98007 in operator() () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:2267
#14 _M_do_set () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/future:527
#15 0x00007f18de683a99 in __pthread_once_slow (once_control=0x7f18d255a708, init_routine=0x7f18d59adac0 <__once_proxy>) at pthread_once.c:116
#16 0x00007f18d3ea4dbb in __gthread_once () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/x86_64-linux-gnu/c++/5.4.0/bits/gthr-default.h:699
#17 call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()> *, bool *), std::__future_base::_S
tate_baseV2 *, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()> *, bool *> ()
    at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/mutex:738
#18 _M_set_result () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/future:386
#19 _M_complete_async () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/future:1606
#20 0x00007f18d3e7a9ba in wait () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/future:319
#21 wait () at /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/future:656
#22 wait () at /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.9/external/hcc-tot/lib/hsa/mcwamp_hsa.cpp:1567
#23 0x00007f18ddfbd92e in ihipStream_t::wait(LockedAccessor<ihipStreamCriticalBase_t<std::mutex> >&) () from /opt/rocm/lib/libhip_hcc.so
#24 0x00007f18ddfbcfd0 in ihipCtx_t::locked_waitAllStreams() () from /opt/rocm/lib/libhip_hcc.so
#25 0x00007f18ddfbceb1 in ihipSynchronize() () from /opt/rocm/lib/libhip_hcc.so
#26 0x00007f18de006c50 in hipDeviceSynchronize () from /opt/rocm/lib/libhip_hcc.so
#27 0x0000000000452a5f in sd_t_d2_2_cuda ()
#28 0x0000000000452be9 in sd_t_d2_2_cuda_ ()
#29 0x0000000001cc8e76 in ccsd_t_doubles_gpu_2_ ()
#30 0x0000000001ccb05a in ccsd_t_doubles_gpu_ ()
#31 0x0000000001ce2a9d in ccsd_t_gpu_ ()
#32 0x0000000002e8d715 in tce_energy (rtdb=0, excitedfragment=.TRUE.) at tce_energy.F:2781
#33 0x0000000002e7ef42 in tce_energy_fragment (rtdb=0) at tce_energy_fragment.F:88
#34 0x00000000004a6c95 in task_energy_doit (rtdb=0, theory=<error reading variable: Cannot access memory at address 0x7fff03856000>, energy=6.0134700169990685e-154, _theory=_theory@entry=32)
    at task_energy.F:299
#35 0x00000000004a82df in task_energy (rtdb=0) at task_energy.F:122
#36 0x000000000049b571 in task (rtdb=0) at task.F:371
#37 0x0000000000493dcf in nwchem () at nwchem.F:318
#38 0x00000000004942cc in main (argc=argc@entry=2, argv=0x7fff03854dd5) at nwchem.F:402
#39 0x00007f18d5336830 in __libc_start_main (main=0x4942af <main>, argc=2, argv=0x7fff03854368, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff03854358)
    at ../csu/libc-start.c:291
#40 0x000000000048fc99 in _start ()
```

**Comment by nartmada** [comment]
@yuq, apologies for the lack of response.  Can you please check latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue has been resolved? Thanks.

**Comment by yuq** [comment]
rocm mpi stack has been refined since then, so I think this ticket is not valid any more.
